/*
 * generated by Xtext 2.28.0
 */
package goldsl.ui;

import com.google.inject.Injector;
import goldsl.ui.internal.GoldslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TasksDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(GoldslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		GoldslActivator activator = GoldslActivator.getInstance();
		return activator != null ? activator.getInjector(GoldslActivator.GOLDSL_TASKSDSL) : null;
	}

}
