/**
 * generated by Xtext 2.28.0
 */
package goldsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TasksDSLIdeModule extends AbstractTasksDSLIdeModule {
}
