/*
 * generated by Xtext 2.28.0
 */
package goldsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTasksDSLScopeProvider extends DelegatingScopeProvider {
}
