/*
 * generated by Xtext 2.28.0
 */
package goldsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TasksDSLUiModule extends AbstractTasksDSLUiModule {
}
