/*
 * generated by Xtext 2.28.0
 */
package goldsl.ui.tests;

import com.google.inject.Injector;
import goldsl.ui.internal.GoldslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TasksDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GoldslActivator.getInstance().getInjector("goldsl.TasksDSL");
	}

}
