/**
 * generated by Xtext 2.28.0
 */
package goldsl.tasksDSL.impl;

import goldsl.tasksDSL.Cell;
import goldsl.tasksDSL.GameOfLife;
import goldsl.tasksDSL.Grid;
import goldsl.tasksDSL.Rule;
import goldsl.tasksDSL.TasksDSLPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Game Of Life</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link goldsl.tasksDSL.impl.GameOfLifeImpl#getGrid <em>Grid</em>}</li>
 *   <li>{@link goldsl.tasksDSL.impl.GameOfLifeImpl#getCells <em>Cells</em>}</li>
 *   <li>{@link goldsl.tasksDSL.impl.GameOfLifeImpl#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GameOfLifeImpl extends MinimalEObjectImpl.Container implements GameOfLife
{
  /**
   * The cached value of the '{@link #getGrid() <em>Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGrid()
   * @generated
   * @ordered
   */
  protected Grid grid;

  /**
   * The cached value of the '{@link #getCells() <em>Cells</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCells()
   * @generated
   * @ordered
   */
  protected EList<Cell> cells;

  /**
   * The cached value of the '{@link #getRules() <em>Rules</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRules()
   * @generated
   * @ordered
   */
  protected EList<Rule> rules;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GameOfLifeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TasksDSLPackage.Literals.GAME_OF_LIFE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Grid getGrid()
  {
    return grid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGrid(Grid newGrid, NotificationChain msgs)
  {
    Grid oldGrid = grid;
    grid = newGrid;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TasksDSLPackage.GAME_OF_LIFE__GRID, oldGrid, newGrid);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGrid(Grid newGrid)
  {
    if (newGrid != grid)
    {
      NotificationChain msgs = null;
      if (grid != null)
        msgs = ((InternalEObject)grid).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TasksDSLPackage.GAME_OF_LIFE__GRID, null, msgs);
      if (newGrid != null)
        msgs = ((InternalEObject)newGrid).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TasksDSLPackage.GAME_OF_LIFE__GRID, null, msgs);
      msgs = basicSetGrid(newGrid, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TasksDSLPackage.GAME_OF_LIFE__GRID, newGrid, newGrid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Cell> getCells()
  {
    if (cells == null)
    {
      cells = new EObjectContainmentEList<Cell>(Cell.class, this, TasksDSLPackage.GAME_OF_LIFE__CELLS);
    }
    return cells;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Rule> getRules()
  {
    if (rules == null)
    {
      rules = new EObjectContainmentEList<Rule>(Rule.class, this, TasksDSLPackage.GAME_OF_LIFE__RULES);
    }
    return rules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TasksDSLPackage.GAME_OF_LIFE__GRID:
        return basicSetGrid(null, msgs);
      case TasksDSLPackage.GAME_OF_LIFE__CELLS:
        return ((InternalEList<?>)getCells()).basicRemove(otherEnd, msgs);
      case TasksDSLPackage.GAME_OF_LIFE__RULES:
        return ((InternalEList<?>)getRules()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TasksDSLPackage.GAME_OF_LIFE__GRID:
        return getGrid();
      case TasksDSLPackage.GAME_OF_LIFE__CELLS:
        return getCells();
      case TasksDSLPackage.GAME_OF_LIFE__RULES:
        return getRules();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TasksDSLPackage.GAME_OF_LIFE__GRID:
        setGrid((Grid)newValue);
        return;
      case TasksDSLPackage.GAME_OF_LIFE__CELLS:
        getCells().clear();
        getCells().addAll((Collection<? extends Cell>)newValue);
        return;
      case TasksDSLPackage.GAME_OF_LIFE__RULES:
        getRules().clear();
        getRules().addAll((Collection<? extends Rule>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TasksDSLPackage.GAME_OF_LIFE__GRID:
        setGrid((Grid)null);
        return;
      case TasksDSLPackage.GAME_OF_LIFE__CELLS:
        getCells().clear();
        return;
      case TasksDSLPackage.GAME_OF_LIFE__RULES:
        getRules().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TasksDSLPackage.GAME_OF_LIFE__GRID:
        return grid != null;
      case TasksDSLPackage.GAME_OF_LIFE__CELLS:
        return cells != null && !cells.isEmpty();
      case TasksDSLPackage.GAME_OF_LIFE__RULES:
        return rules != null && !rules.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //GameOfLifeImpl
