/*
 * generated by Xtext 2.28.0
 */
package goldsl.ide

import com.google.inject.Guice
import goldsl.TasksDSLRuntimeModule
import goldsl.TasksDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TasksDSLIdeSetup extends TasksDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TasksDSLRuntimeModule, new TasksDSLIdeModule))
	}
	
}
