/**
 * generated by Xtext 2.28.0
 */
package goldsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class TasksDSLQuickfixProvider extends DefaultQuickfixProvider {
}
