/**
 * generated by Xtext 2.28.0
 */
package goldsl.tasksDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link goldsl.tasksDSL.Cell#getX <em>X</em>}</li>
 *   <li>{@link goldsl.tasksDSL.Cell#getY <em>Y</em>}</li>
 *   <li>{@link goldsl.tasksDSL.Cell#getNo <em>No</em>}</li>
 *   <li>{@link goldsl.tasksDSL.Cell#getDir <em>Dir</em>}</li>
 * </ul>
 *
 * @see goldsl.tasksDSL.TasksDSLPackage#getCell()
 * @model
 * @generated
 */
public interface Cell extends EObject
{
  /**
   * Returns the value of the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>X</em>' attribute.
   * @see #setX(int)
   * @see goldsl.tasksDSL.TasksDSLPackage#getCell_X()
   * @model
   * @generated
   */
  int getX();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Cell#getX <em>X</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X</em>' attribute.
   * @see #getX()
   * @generated
   */
  void setX(int value);

  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(int)
   * @see goldsl.tasksDSL.TasksDSLPackage#getCell_Y()
   * @model
   * @generated
   */
  int getY();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Cell#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(int value);

  /**
   * Returns the value of the '<em><b>No</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>No</em>' attribute.
   * @see #setNo(int)
   * @see goldsl.tasksDSL.TasksDSLPackage#getCell_No()
   * @model
   * @generated
   */
  int getNo();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Cell#getNo <em>No</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>No</em>' attribute.
   * @see #getNo()
   * @generated
   */
  void setNo(int value);

  /**
   * Returns the value of the '<em><b>Dir</b></em>' attribute.
   * The literals are from the enumeration {@link goldsl.tasksDSL.Direction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dir</em>' attribute.
   * @see goldsl.tasksDSL.Direction
   * @see #setDir(Direction)
   * @see goldsl.tasksDSL.TasksDSLPackage#getCell_Dir()
   * @model
   * @generated
   */
  Direction getDir();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Cell#getDir <em>Dir</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dir</em>' attribute.
   * @see goldsl.tasksDSL.Direction
   * @see #getDir()
   * @generated
   */
  void setDir(Direction value);

} // Cell
