/**
 * generated by Xtext 2.28.0
 */
package goldsl.tasksDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game Of Life</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link goldsl.tasksDSL.GameOfLife#getGrid <em>Grid</em>}</li>
 *   <li>{@link goldsl.tasksDSL.GameOfLife#getCells <em>Cells</em>}</li>
 *   <li>{@link goldsl.tasksDSL.GameOfLife#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see goldsl.tasksDSL.TasksDSLPackage#getGameOfLife()
 * @model
 * @generated
 */
public interface GameOfLife extends EObject
{
  /**
   * Returns the value of the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grid</em>' containment reference.
   * @see #setGrid(Grid)
   * @see goldsl.tasksDSL.TasksDSLPackage#getGameOfLife_Grid()
   * @model containment="true"
   * @generated
   */
  Grid getGrid();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.GameOfLife#getGrid <em>Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grid</em>' containment reference.
   * @see #getGrid()
   * @generated
   */
  void setGrid(Grid value);

  /**
   * Returns the value of the '<em><b>Cells</b></em>' containment reference list.
   * The list contents are of type {@link goldsl.tasksDSL.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cells</em>' containment reference list.
   * @see goldsl.tasksDSL.TasksDSLPackage#getGameOfLife_Cells()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getCells();

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference list.
   * The list contents are of type {@link goldsl.tasksDSL.Rule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference list.
   * @see goldsl.tasksDSL.TasksDSLPackage#getGameOfLife_Rules()
   * @model containment="true"
   * @generated
   */
  EList<Rule> getRules();

} // GameOfLife
