/**
 * generated by Xtext 2.28.0
 */
package goldsl.tasksDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link goldsl.tasksDSL.Rule#getType <em>Type</em>}</li>
 *   <li>{@link goldsl.tasksDSL.Rule#getSign <em>Sign</em>}</li>
 *   <li>{@link goldsl.tasksDSL.Rule#getN <em>N</em>}</li>
 * </ul>
 *
 * @see goldsl.tasksDSL.TasksDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link goldsl.tasksDSL.RuleType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see goldsl.tasksDSL.RuleType
   * @see #setType(RuleType)
   * @see goldsl.tasksDSL.TasksDSLPackage#getRule_Type()
   * @model
   * @generated
   */
  RuleType getType();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Rule#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see goldsl.tasksDSL.RuleType
   * @see #getType()
   * @generated
   */
  void setType(RuleType value);

  /**
   * Returns the value of the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sign</em>' attribute.
   * @see #setSign(String)
   * @see goldsl.tasksDSL.TasksDSLPackage#getRule_Sign()
   * @model
   * @generated
   */
  String getSign();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Rule#getSign <em>Sign</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sign</em>' attribute.
   * @see #getSign()
   * @generated
   */
  void setSign(String value);

  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(int)
   * @see goldsl.tasksDSL.TasksDSLPackage#getRule_N()
   * @model
   * @generated
   */
  int getN();

  /**
   * Sets the value of the '{@link goldsl.tasksDSL.Rule#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(int value);

} // Rule
