/**
 * generated by Xtext 2.28.0
 */
package goldsl.tasksDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see goldsl.tasksDSL.TasksDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TasksDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tasksDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.TasksDSL.goldsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tasksDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TasksDSLPackage eINSTANCE = goldsl.tasksDSL.impl.TasksDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.impl.GameOfLifeImpl <em>Game Of Life</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.impl.GameOfLifeImpl
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getGameOfLife()
   * @generated
   */
  int GAME_OF_LIFE = 0;

  /**
   * The feature id for the '<em><b>Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE__CELLS = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE__RULES = 1;

  /**
   * The number of structural features of the '<em>Game Of Life</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_OF_LIFE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.impl.CellImpl
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 1;

  /**
   * The feature id for the '<em><b>NCells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__NCELLS = 0;

  /**
   * The feature id for the '<em><b>Fill Cells</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__FILL_CELLS = 1;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.impl.NormalCellImpl <em>Normal Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.impl.NormalCellImpl
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getNormalCell()
   * @generated
   */
  int NORMAL_CELL = 2;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CELL__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CELL__Y = 1;

  /**
   * The number of structural features of the '<em>Normal Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.impl.FillCellImpl <em>Fill Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.impl.FillCellImpl
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getFillCell()
   * @generated
   */
  int FILL_CELL = 3;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_CELL__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_CELL__Y = 1;

  /**
   * The feature id for the '<em><b>Rep Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_CELL__REP_AMOUNT = 2;

  /**
   * The feature id for the '<em><b>Dir</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_CELL__DIR = 3;

  /**
   * The number of structural features of the '<em>Fill Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_CELL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.impl.RuleImpl
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 4;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__TYPE = 0;

  /**
   * The feature id for the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__SIGN = 1;

  /**
   * The feature id for the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__N = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.Direction <em>Direction</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.Direction
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getDirection()
   * @generated
   */
  int DIRECTION = 5;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.RuleType <em>Rule Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.RuleType
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getRuleType()
   * @generated
   */
  int RULE_TYPE = 6;

  /**
   * The meta object id for the '{@link goldsl.tasksDSL.CompareSign <em>Compare Sign</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see goldsl.tasksDSL.CompareSign
   * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getCompareSign()
   * @generated
   */
  int COMPARE_SIGN = 7;


  /**
   * Returns the meta object for class '{@link goldsl.tasksDSL.GameOfLife <em>Game Of Life</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Of Life</em>'.
   * @see goldsl.tasksDSL.GameOfLife
   * @generated
   */
  EClass getGameOfLife();

  /**
   * Returns the meta object for the containment reference list '{@link goldsl.tasksDSL.GameOfLife#getCells <em>Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cells</em>'.
   * @see goldsl.tasksDSL.GameOfLife#getCells()
   * @see #getGameOfLife()
   * @generated
   */
  EReference getGameOfLife_Cells();

  /**
   * Returns the meta object for the containment reference list '{@link goldsl.tasksDSL.GameOfLife#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see goldsl.tasksDSL.GameOfLife#getRules()
   * @see #getGameOfLife()
   * @generated
   */
  EReference getGameOfLife_Rules();

  /**
   * Returns the meta object for class '{@link goldsl.tasksDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see goldsl.tasksDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the containment reference list '{@link goldsl.tasksDSL.Cell#getNCells <em>NCells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>NCells</em>'.
   * @see goldsl.tasksDSL.Cell#getNCells()
   * @see #getCell()
   * @generated
   */
  EReference getCell_NCells();

  /**
   * Returns the meta object for the containment reference list '{@link goldsl.tasksDSL.Cell#getFillCells <em>Fill Cells</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fill Cells</em>'.
   * @see goldsl.tasksDSL.Cell#getFillCells()
   * @see #getCell()
   * @generated
   */
  EReference getCell_FillCells();

  /**
   * Returns the meta object for class '{@link goldsl.tasksDSL.NormalCell <em>Normal Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Cell</em>'.
   * @see goldsl.tasksDSL.NormalCell
   * @generated
   */
  EClass getNormalCell();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.NormalCell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see goldsl.tasksDSL.NormalCell#getX()
   * @see #getNormalCell()
   * @generated
   */
  EAttribute getNormalCell_X();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.NormalCell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see goldsl.tasksDSL.NormalCell#getY()
   * @see #getNormalCell()
   * @generated
   */
  EAttribute getNormalCell_Y();

  /**
   * Returns the meta object for class '{@link goldsl.tasksDSL.FillCell <em>Fill Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill Cell</em>'.
   * @see goldsl.tasksDSL.FillCell
   * @generated
   */
  EClass getFillCell();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.FillCell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see goldsl.tasksDSL.FillCell#getX()
   * @see #getFillCell()
   * @generated
   */
  EAttribute getFillCell_X();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.FillCell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see goldsl.tasksDSL.FillCell#getY()
   * @see #getFillCell()
   * @generated
   */
  EAttribute getFillCell_Y();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.FillCell#getRepAmount <em>Rep Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Rep Amount</em>'.
   * @see goldsl.tasksDSL.FillCell#getRepAmount()
   * @see #getFillCell()
   * @generated
   */
  EAttribute getFillCell_RepAmount();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.FillCell#getDir <em>Dir</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dir</em>'.
   * @see goldsl.tasksDSL.FillCell#getDir()
   * @see #getFillCell()
   * @generated
   */
  EAttribute getFillCell_Dir();

  /**
   * Returns the meta object for class '{@link goldsl.tasksDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see goldsl.tasksDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.Rule#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see goldsl.tasksDSL.Rule#getType()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Type();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.Rule#getSign <em>Sign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sign</em>'.
   * @see goldsl.tasksDSL.Rule#getSign()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Sign();

  /**
   * Returns the meta object for the attribute '{@link goldsl.tasksDSL.Rule#getN <em>N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>N</em>'.
   * @see goldsl.tasksDSL.Rule#getN()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_N();

  /**
   * Returns the meta object for enum '{@link goldsl.tasksDSL.Direction <em>Direction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Direction</em>'.
   * @see goldsl.tasksDSL.Direction
   * @generated
   */
  EEnum getDirection();

  /**
   * Returns the meta object for enum '{@link goldsl.tasksDSL.RuleType <em>Rule Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Rule Type</em>'.
   * @see goldsl.tasksDSL.RuleType
   * @generated
   */
  EEnum getRuleType();

  /**
   * Returns the meta object for enum '{@link goldsl.tasksDSL.CompareSign <em>Compare Sign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Compare Sign</em>'.
   * @see goldsl.tasksDSL.CompareSign
   * @generated
   */
  EEnum getCompareSign();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TasksDSLFactory getTasksDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.impl.GameOfLifeImpl <em>Game Of Life</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.impl.GameOfLifeImpl
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getGameOfLife()
     * @generated
     */
    EClass GAME_OF_LIFE = eINSTANCE.getGameOfLife();

    /**
     * The meta object literal for the '<em><b>Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_OF_LIFE__CELLS = eINSTANCE.getGameOfLife_Cells();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_OF_LIFE__RULES = eINSTANCE.getGameOfLife_Rules();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.impl.CellImpl
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>NCells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__NCELLS = eINSTANCE.getCell_NCells();

    /**
     * The meta object literal for the '<em><b>Fill Cells</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CELL__FILL_CELLS = eINSTANCE.getCell_FillCells();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.impl.NormalCellImpl <em>Normal Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.impl.NormalCellImpl
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getNormalCell()
     * @generated
     */
    EClass NORMAL_CELL = eINSTANCE.getNormalCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMAL_CELL__X = eINSTANCE.getNormalCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMAL_CELL__Y = eINSTANCE.getNormalCell_Y();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.impl.FillCellImpl <em>Fill Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.impl.FillCellImpl
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getFillCell()
     * @generated
     */
    EClass FILL_CELL = eINSTANCE.getFillCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_CELL__X = eINSTANCE.getFillCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_CELL__Y = eINSTANCE.getFillCell_Y();

    /**
     * The meta object literal for the '<em><b>Rep Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_CELL__REP_AMOUNT = eINSTANCE.getFillCell_RepAmount();

    /**
     * The meta object literal for the '<em><b>Dir</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILL_CELL__DIR = eINSTANCE.getFillCell_Dir();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.impl.RuleImpl
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__TYPE = eINSTANCE.getRule_Type();

    /**
     * The meta object literal for the '<em><b>Sign</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__SIGN = eINSTANCE.getRule_Sign();

    /**
     * The meta object literal for the '<em><b>N</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__N = eINSTANCE.getRule_N();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.Direction <em>Direction</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.Direction
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getDirection()
     * @generated
     */
    EEnum DIRECTION = eINSTANCE.getDirection();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.RuleType <em>Rule Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.RuleType
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getRuleType()
     * @generated
     */
    EEnum RULE_TYPE = eINSTANCE.getRuleType();

    /**
     * The meta object literal for the '{@link goldsl.tasksDSL.CompareSign <em>Compare Sign</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see goldsl.tasksDSL.CompareSign
     * @see goldsl.tasksDSL.impl.TasksDSLPackageImpl#getCompareSign()
     * @generated
     */
    EEnum COMPARE_SIGN = eINSTANCE.getCompareSign();

  }

} //TasksDSLPackage
