/**
 * generated by Xtext 2.28.0
 */
package goldsl.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class TasksDSLProposalProvider extends AbstractTasksDSLProposalProvider {
}
