/**
 * generated by Xtext 2.28.0
 */
package goldsl;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TasksDSLStandaloneSetup extends TasksDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new TasksDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
