/*
 * generated by Xtext 2.28.0
 */
package goldsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TasksDSLStandaloneSetup extends TasksDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TasksDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
