/*
 * generated by Xtext 2.28.0
 */
package goldsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TasksDSLRuntimeModule extends AbstractTasksDSLRuntimeModule {
}
